services:
  frontend:
    build:
      context: ./frontend  # This tells Docker: "Go into the frontend folder first"
      dockerfile: Dockerfile # "Now look for the Dockerfile here"
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true